name: unit test

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    container: golang:1.24
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run unit tests
        run: |
          go test -v ./...
